### ISSUE TITLE
Support comma-separated output

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/speedtest-cli-extras#1]
Currently it's not safe to use commas for separated values, because some servers return some values with commas rather than periods (probably due to their locale settings).

One solution would be to bluntly replace any commas with periods (in each of the fields/variables) before generating the one-line output, e.g. via `sed`.

Contributions appreciated.

**Comment by St0ner1995** [comment]
if you use quotation marks like this it wont be an issue:
"2016-04-02 19:14:04","2016-04-02 19:14:50","*****","*.*.*.*","SoftLayer Technologies, Inc. (Melbourne)","12.18 km","38.572 ms","13.17 Mbit/s","0.84 Mbit/s","http://www.speedtest.net/result/**********.png"

**Comment by St0ner1995** [comment]
i made changes to my copy to fix this but i have not figured out github. its a very simple change anyway

**Comment by St0ner1995** [comment]
I have a fork with the changes if you would like to take a look

**Comment by HenrikBengtsson** [comment]
Thanks for this.  I've finally got around to do some updates that I wanted, which resulted in quite a few updates (all backward compatible for now):
```sh
% speedtest-csv --help
Usage:
 speedtest-csv [options]

Options:
 --debug        Output extra debug information
 --header       Display field names (only)
 --help         This help
 --last         Use most recent stats, iff available
 --quote <str>  Use <str> as quotation mark
 --sep <str>    Use <str> as field separator
 --standardize  Standardize units and number formats
 --version      Display version

Example:
 speedtest-csv --standardize --sep '\t'

Copyright: 2014-2016 Henrik Bengtsson
License: GPL (>= 2.1) [http://www.gnu.org/licenses/gpl.html]
```

With this, it is possible to use comma-separated tags and add quotation marks using:
```sh
$ speedtest-csv --standardize --sep ',' --quote '"'
"2016-04-03 20:11:02","2016-04-03 20:11:02","University of California - Office of the","169.230.134.141","Unwired (San Francisco, CA)","3.78 km","5.663 ms","743.21 Mbit/s","316.27 Mbit/s","http://www.speedtest.net/result/5222536160.png"
```
One can also output TAB-delimited output, e.g.
```sh
n14{henrik}: ./speedtest-csv --standardize --sep '\t' --last
2016-04-03 20:12:12     2016-04-03 20:12:12     University of California - Office of the        169.230.134.141 Unwired (San Francisco, CA)      3.78 km 5.663 ms        743.21 Mbit/s   316.27 Mbit/s   http://www.speedtest.net/result/5222536160.png
```
Note how I use the new `--last` option, which skips querying the Speedtest server but instead using the most recent stats.
