### ISSUE TITLE
Defeat default use of --share in call to speedtest-cli?

### ISSUE THREAD

**Issue by RERobbins** [HenrikBengtsson/speedtest-cli-extras#13]
Is there a way to invoke speedtest-csv so that it does not use the --share argument when it calls speedtest-cli?  I realize I can change the script myself to simply eliminate the use of that argument.

**Comment by HenrikBengtsson** [comment]
Sorry, it's currently hard coded.   I guess there should be a `--no-share` and / or a `--share` option.

I general it would make sense to have `--no-*` options for almost everything, e.g. `--no-standardize`.  This would allow to change the default behavior in the future, having `--standardize` to be the default wouldn't hurt.

**Comment by RERobbins** [comment]
Why do you need to do anything at all?  The code already lets users specify speedtest-cli arguments to speedtest-csv and it passes them along, right?  If that's correct then why not eliminate the explicit use of that argument in speedtest-csv.  If a user wants --share then wouldn't adding "--share" to the invocation of speedtest-csv just result in that argument being passed along to speedtest-cli?

**Comment by HenrikBengtsson** [comment]
Yes, that would work.  But if one wants `speedtest-csv` to have different defaults, then it needs to explicitly replicate the parameters of `speedtest-cli` (and add `--no-*` options).

**Comment by RERobbins** [comment]
I understand.

**Comment by RERobbins** [comment]
Do speedtest prohibit simultaneous calls?  I want to test against several servers, including my own mini server, by forking several processes and waiting until all are completed before adding the results to a file that's used to generate an R data set.  Things seem to work when I run each process in a serial fashion but I'm struggling to get sensible results when I run them in parallel.

One of the first errors I encountered was a message that I can't run speedtest and get a png share file when I'm also running against a speedtest mini server at the same time.  That's why I wanted to disable the --share argument.  In the end I might just give up and run each process in a serial fashion.

**Comment by HenrikBengtsson** [comment]
No idea. I would ask this over at speedtest-cli since that's where all the action is actually happening.

**Comment by HenrikBengtsson** [comment]
I've just released v1.2.0 which now supports:
```sh
speedtest-csv --sep '\t' --standardize --no-share
```
