### ISSUE TITLE
Speedtest-csv Stopped Working with Speedtest.net beta

### ISSUE THREAD

**Issue by russinsight** [HenrikBengtsson/speedtest-cli-extras#20]
Without any action on my part speedtest-csv stopped working between 1500 and 1600 on 8th of June. Trouble shooting I discover that speedtest.net how has a new display http://beta.speedtest.net.  If this is the real problem, will there be a code update?  How should I modify speedtest-csv to work with the beta version of speedtest.net.  

Thank you for your replay and assistance is restoring this excellent device.

**Comment by HenrikBengtsson** [comment]
Works for me:
```sh
$ speedtest-csv
2017-06-20 14:28:24	2017-06-20 14:28:49	XFINITY	24.130.241.250	Comcast (San Francisco, CA)	18.34	16.0	9.97	1.89	http://www.speedtest.net/result/6393266885.png
```
with
```sh
$ speedtest-csv --version
2.0.1
$ speedtest-cli --version
1.0.6
```
Since all `speedtest-csv` is really doing is calling `speedtest-cli` and reformat the output, you can troubleshoot any connection problems by calling the latter directly, e.g.
```sh
$ speedtest-cli
Retrieving speedtest.net configuration...
Testing from XFINITY (24.130.241.250)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Comcast (San Francisco, CA) [18.34 km]: 58.979 ms
Testing download speed................................................................................
Download: 6.37 Mbit/s
Testing upload speed................................................................................................
Upload: 2.06 Mbit/s
```

**Comment by HenrikBengtsson** [comment]
No further "traffic" here.  Assuming it was a hiccup.  Closing...
