### ISSUE TITLE
server id

### ISSUE THREAD

**Issue by fohnbit** [HenrikBengtsson/speedtest-cli-extras#21]
Hello,

is it possible to set the server ID´s? He check always with the closest ... but I want to set the server for speedtest.

speedtest-cli can use the server id: --server SERVER

Thank you!

**Comment by HenrikBengtsson** [comment]
From `speedtest-csv --help`:

```
speedtest-csv 2.0.1

Usage:
 speedtest-csv [options]

Options:
[...]
Any other options are passed to speedtest-cli as is.
```

**Comment by fohnbit** [comment]
oh, ok. Thank you! :-)
