### ISSUE TITLE
When called in CRON log is empty

### ISSUE THREAD

**Issue by SilverDay** [HenrikBengtsson/speedtest-cli-extras#4]
Hi when I call speedlink-csv >> /home/pi/speedlink.log using cron, I get a dtae and time and the following fields are all empty. Basically it is just a number of ; with no content!

**Comment by normcyr** [comment]
I had to change the line 52 of the `speedtest-csv` script to match the path where `speedtest_cli.py` is. Then everything was fine. Did `speedtest_cli.py` give you an output as expected?

**Comment by SilverDay** [comment]
Thank you! That worked perfectly!
